### ISSUE TITLE
How to pass props from parent route component into child route component

### ISSUE THREAD

**Issue by TSMMark** [dannyvassallo/node-react-boilerplate#11]
Found [an example](https://github.com/reactjs/react-router/blob/master/examples/passing-props-to-children/app.js#L55-L57) of how to pass props from a parent route into a child route.

Modified the example below to pass state from the top-level router component and into the child route:

### [App.jsx](https://github.com/dannyvassallo/node-react-boilerplate/blob/master/client/app/components/App.jsx)

```jsx
<div>
  <NavBar />
  <main>
    {this.props.children && React.cloneElement(this.props.children, {
      counter: this.state.counter
    })}
  </main>
</div>
```

Then you can reference `counter` in a specific `Counter.jsx` route or something, via `this.props.counter`.

**Comment by TSMMark** [comment]
One reason flux is a cool pattern is that you can call your flux actions from any component, and you don't have to bubble up callback listeners all the way up and down the component tree. So you can move [`_myAction`](https://github.com/dannyvassallo/node-react-boilerplate/blob/master/client/app/components/App.jsx#L43) from `App.jsx` into `Counter.jsx`, and still make calls to `Store.dispatch`.

**Comment by dannyvassallo** [comment]
@TSMMark thx!

**Comment by TSMMark** [comment]
@dannyvassallo it works?

**Comment by dannyvassallo** [comment]
@TSMMark yeah looking like it -- checkout the repo I merged in the refactor branch. The counter is in it's own component now and inherits the integer value from state.
